# Generated by Django 3.2.9 on 2021-12-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
                ('author', models.ManyToManyField(to='blog.Author')),
                ('post', models.ManyToManyField(to='blog.Post')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
